version: "3" # Docker compose의 버전 선택
services: # 컨테이너의 이름, 이미지, 포트 등을 정의하여 컨테이너 생성 및 관리
  app:
    image: wido1593/guest-book-spring-boot:latest # 기반이 되는 이미지 지정
    container_name: guest-book-spring-boot # 생성될 컨테이너 이름 정의
    expose:
      - 18080
    ports:
      - ${SPRING_BOOT_PORT_PROD}:18080
    depends_on: # 의존성 주입으로 해당 서비스가 먼저 생성, 실행된다
      - mongodb
    networks:
      - guest-book

  mongodb:
    image: mongo:7.0.5
    container_name: guest-book-mongodb
    hostname: mongodb
    volumes:
      - ~/mongodb:/data/db
    restart: always # 재시작 정책
    command: ["--auth", "--bind_ip", "0.0.0.0"]
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - guest-book

networks:
  guest-book:
    driver: bridge