
# 현재 애플리케이션이 구동되는 기반 이미지 버전 pull
FROM openjdk:17

# 작성자, 관리자 등의 정보를 나타낼 수 있다.
LABEL maintainer='wido1593@gmail.com'

#JAR 파일을 생성하기 위해 Gradle 빌드(CMD는 컨테이너가 실행되기 전)
CMD ["./gradlew", "clean", "build"]

# JAR 파일 경로 변수로 지정.
ARG JAR_FILE=build/libs/*.jar

# JAR 파일을 app.jar 라는 이름으로 사용하기 위해 복사.
COPY ${JAR_FILE} app.jar
# 운영/개발 분리 시 설정 값을 적용하기 위해
COPY src/main/resources/application-dev.yml application.yml

#Docker Image를 8080으로 외부에 노출
EXPOSE 8080

# JAR를 실행하기 위한 java -jar app.jar 명령어를 ENTRYPOINT로 설정(ENTRYPOINT는 컨테이너가 실행될 떄)
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=dev", "app.jar"]