jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    key: jaehoonman

spring:
  data:
    mongodb:
      database: guest_book
      username: ENC(e9o/MQco15mNOF6baawm+rOoF76SXSf72QPVn4G5/Ktb77/HDKu+yvVpfN3lpvgk)
      password: ENC(OvVpePRkS5sr+8yHGFc5ATzrV4l3tBYLF23z40aD818qgrre+O1YiGaSSZEXJWCf)
      authentication-database: admin
      host: mongodb
      port: 27017

server:
  port: 8080